### ISSUE TITLE
Add support for limiting the scan

### ISSUE THREAD

**Issue by soundslocke** [GigSalad/node-redis-scan#4]
It would be useful in some contexts to have an option for limiting the scan. At times we only want to scan until returning the first matching key or the first `n` matching keys. This would lend itself to `scan()` as well as `eachScan()` (plus the specific variants of these).

Similar functionality could be achieved if the client is able to cancel any scan in progress though this approach would only lend itself to `eachScan()`.

**Comment by ghost** [comment]
Is this gonna be done anytime soon? Looking forward to it......

**Comment by soundslocke** [comment]
This functionality has been added in [v1.3.0](https://github.com/GigSalad/node-redis-scan/releases/tag/v1.3.0)!
